# Font
[font]
size = 12.0
[font.normal]
family = 'JetBrainsMonoNL Nerd Font'
style  = 'Regular'
[font.bold]
family = 'JetBrainsMonoNL Nerd Font'
style  = 'Bold'
[font.italic]
family = 'JetBrainsMonoNL Nerd Font'
style  = 'Italic'
[font.bold_italic]
family = 'JetBrainsMonoNL Nerd Font'
style  = 'Bold Italic'
[window]
startup_mode = 'Maximized'

# Colors (One Dark)
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

# Keyboard
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B[13;2u"
